import foto from "../img/foto.png";

export const itens = [
    {nome: "Das Man",
    descricao: "alguma descricao1",
    imagem: foto,
    cor: "#66b2ff"}, 
    {nome: "Segundo Nome",
    descricao: "outra descricao2",
    imagem: foto,
    cor: "#66b2ff"},
    {nome: "Terceiro Nome",
    descricao: "outra descricao3",
    imagem: foto,
    cor: "#66b2ff"},
    {nome: "Quarto Nome",
    descricao: "outra descricao4",
    imagem: foto,
    cor: "#66b2ff"},
    {nome: "Quinto Nome",
    descricao: "outra descricao5",
    imagem: foto,
    cor: "#66b2ff"},
    {nome: "Sexto Nome",
    descricao: "outra descricao6",
    imagem: foto,
    cor: "#66b2ff"},
    {nome: "Sétimo Nome",
    descricao: "outra descricao7",
    imagem: foto,
    cor: "#66b2ff"},
    {nome: "Oitavo Nome",
    descricao: "outra descricao8",
    imagem: foto,
    cor: "#66b2ff"}
  ];